SELECT 
    DATE_TRUNC('month', o.ORDER_DATE) AS SALES_MONTH, 
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_SUCCESSFUL_ORDERS,
    SUM(d.GROSS_AMOUNT - (d.GROSS_AMOUNT * (d.DISCOUNT_PERCENT / 100))) AS NET_REVENUE
FROM {{ ref('stg_orders') }} o
JOIN {{ ref('int_order_discounts') }} d ON o.ORDER_ID = d.ORDER_ID
GROUP BY 1