name: 'enterprise_data_mesh'
version: '1.0.0'
config-version: 2

profile: 'default'
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  enterprise_data_mesh:
    
    # 1. STAGING (Shared Compute & Storage Optimization)
    staging:
      +materialized: table
      +transient: true
      +schema: STAGING
      +snowflake_warehouse: ADMIN_WH

    # 2. MARTS (Departmental Data Mesh & FinOps Compute)
    marts:
      +materialized: table
      
      core:
        +schema: CORE_ANALYTICS
        +group: core
        +snowflake_warehouse: ADMIN_WH
        
      finance:
        +schema: FINANCE_ANALYTICS
        +group: finance
        +snowflake_warehouse: FINANCE_WH
        +tags: ["finance_run"]
        
      hr:
        +schema: HR_ANALYTICS
        +group: hr
        +snowflake_warehouse: HR_WH
        +tags: ["hr_run"]

      marketing:
        +schema: MARKETING_ANALYTICS
        +group: marketing
        +snowflake_warehouse: MARKETING_WH
        +tags: ["marketing_run"]

      supply_chain:
        +schema: SUPPLY_CHAIN_ANALYTICS
        +group: supply_chain
        +snowflake_warehouse: SUPPLY_CHAIN_WH
        +tags: ["sc_run"]

